# Generated by Django 4.0.4 on 2022-04-17 15:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itineraires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraire',
            name='difficulte_estimee',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie', models.DateField()),
                ('duree_reelle', models.IntegerField()),
                ('nombre_participants', models.IntegerField()),
                ('experience_groupe', models.CharField(choices=[('TD', 'Tous débutants'), ('TE', 'Tous expérimentés'), ('MI', 'Mixte')], default='TD', max_length=2)),
                ('meteo', models.CharField(choices=[('BO', 'Bonne'), ('MO', 'Moyenne'), ('MA', 'Mauvaise')], default='MO', max_length=2)),
                ('difficulte_ressentie', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.itineraire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
